/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-07-02 07:06:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1623825654610L));
    _jspx_dependants.put("jar:file:/C:/workspace/springMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TeamProject_022_Weather/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 10;\r\n");
      out.write("\tpadding: 10;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: linear-gradient(130deg, #7389d0, #eebdc3);\r\n");
      out.write("\tbackground-attachment: fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1, h4 {\r\n");
      out.write("\t/* 상단 로고 부분 */\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-shadow: 0px 0px 20px rgb(234, 237, 176);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 70px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes sparkle {from { background-position:0%100%;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\tbackground-position: 200% 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("section {\r\n");
      out.write("\t/* 개인정보 등록하는 부분을 감싼 옅은 선 */\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tjustify-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("fieldset {\r\n");
      out.write("\t/* 개인정보 등록하는 부분을 감싼 옅은 선 */\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tjustify-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinTable th, .joinTable td {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tborder-bottom: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinTable th {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("\tborder-radius: 15px;\r\n");
      out.write("\tmargin: 10px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinTable td {\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("}\r\n");
      out.write(".joinTable td#id_check {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinTable .textForm {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinTable:hover .textForm:hover {\r\n");
      out.write("\tanimation: sparkle 4s infinite linear;\r\n");
      out.write("\tbackground: linear-gradient(90deg, #7389d0, #eebdc3, #7389d0);\r\n");
      out.write("\tbackground-size: 300% 100%;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tz-index: -1;\r\n");
      out.write("\ttransform: scale(0.99) translateY(3px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinTable .btn {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tcolor: rgb(90, 90, 90);\r\n");
      out.write("\ttransition: all 0.3s ease-out;\r\n");
      out.write("\tbackground: linear-gradient(270deg, rgba(223, 190, 106, 0.8),\r\n");
      out.write("\t\trgba(146, 111, 52, 0.8), rgba(34, 34, 34, 0), rgba(34, 34, 34, 0));\r\n");
      out.write("\tbackground-position: 1% 50%;\r\n");
      out.write("\tbackground-size: 300% 300%;\r\n");
      out.write("\tborder: 1px solid rgba(223, 190, 106, 0.3);\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("\tbackground-position: 99% 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>Sign Up</h1>\r\n");
      out.write("\t<h4>WEATHER & OOTD</h4>\r\n");
      out.write("\t<section id=\"join_wrap\">\r\n");
      out.write("\t\t<form class=\"mem_join\" method=\"POST\">\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<table class=\"joinTable\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"first\"><label for=\"us_id\">ID</label></th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td >\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"us_id\" name=\"us_id\" class=\"textForm\" placeholder=\"ID를 입력...\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"id_check\" type=\"button\">중복확인</button>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"user_pwd\">PW</label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" id=\"us_pw\" name=\"us_pw\" class=\"textForm\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"비밀번호를 입력...\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t <tr>\r\n");
      out.write("            <th><label for=\"user_pwd_check\">PW(check)</label></th>\r\n");
      out.write("            <td><input type=\"password\" id=\"us_pw_ch\" class=\"textForm\" placeholder=\"비밀번호를 재확인...\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"us_name\">이름</label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"us_name\" class=\"textForm\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"이름을 입력...\">\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>지역선택</th>\r\n");
      out.write("\t\t\t\t\t\t<td><select name=\"us_city\" class=\"textForm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>서울</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>대전</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>대구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>부산</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>광주</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>경기도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>강원도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>충청북도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>충청남도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>전라북도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>전라남도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>경상북도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>경상남도</option>\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>상세주소</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"us_dist\" class=\"textForm\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn\">가입하기</button>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</section>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("// document.querySelector(\"table.joinTable\").addEventListener(\"click\", (e)=>{\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t  let objId = document.querySelector(\"td input#us_id\");\r\n");
      out.write("\t  let objPw1 = document.querySelector(\"td input#us_pw\");\r\n");
      out.write("\t  let objPw2 = document.querySelector(\"td input#us_pw_ch\");\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  document.querySelector(\"button#id_check\").addEventListener(\"click\", ()=> {\r\n");
      out.write("\t\t  let json = { objId };\r\n");
      out.write("\t\t  let jsonString = JSON.stringify(json);\r\n");
      out.write("\t\t  fetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rootPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/idcheck/\" + objId.value)\r\n");
      out.write("\t\t  .then(res=>res.text())\r\n");
      out.write("\t\t  .then(result=>{\r\n");
      out.write("\t\t\t  if(result == \"1\") {\r\n");
      out.write("\t\t\t\t  alert(\"이미 사용중인 아이디 입니다.\")\r\n");
      out.write("\t\t\t\t  objId.focus();\r\n");
      out.write("\t\t\t\t  objId.value = \"\"\r\n");
      out.write("\t\t\t\t  return false;\r\n");
      out.write("\t\t\t  } else {\r\n");
      out.write("\t\t\t\t  alert(\"사용할 수 있는 아이디 입니다.\")\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t  })\r\n");
      out.write("\t\t  \t\t// , {\r\n");
      out.write("\t\t\t  \t// method:\"POST\",\r\n");
      out.write("\t\t\t\t// body : jsonString,\r\n");
      out.write("\t\t\t\t// headers : {\r\n");
      out.write("\t\t\t\t// \t\"content-Type\" : \"applications/json\"\t\r\n");
      out.write("\t\t\t\t// }\r\n");
      out.write("\t\t  // })\r\n");
      out.write("\t\t  \r\n");
      out.write("\t  })\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  document.querySelector(\"button.btn\").addEventListener(\"click\", ()=> {\r\n");
      out.write("\t\t  \r\n");
      out.write("\t  if((objId.value) == \"\") {\r\n");
      out.write("\t\t  alert(\"ID를 입력하세요\")\r\n");
      out.write("\t\t  objId.focus();\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if ((objPw1.value) == \"\"){\r\n");
      out.write("          alert(\"비밀번호를 입력해 주세요\");\r\n");
      out.write("          objPw1.focus();\r\n");
      out.write("          return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ((objPw2.value)==\"\"){\r\n");
      out.write("          alert(\"비밀번호를 입력해 주세요\");\r\n");
      out.write("          objPw2.focus();\r\n");
      out.write("          return false;\r\n");
      out.write("      }\r\n");
      out.write("      if((objPw1.value) !== (objPw2.value)) {\r\n");
      out.write("    \t alert(\"비밀번호가 일치하지 않습니다.\")\r\n");
      out.write("    \t objPw1.focus();\r\n");
      out.write("    \t return false;\r\n");
      out.write("      }\r\n");
      out.write("      document.querySelector(\"form.mem_join\").submit();\r\n");
      out.write("\t  })\r\n");
      out.write("// })\r\n");
      out.write("  </script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/join.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("rootPath");
      // /WEB-INF/views/join.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/join.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
